import {
  Gift,
  Trophy,
  Rocket,
  Gem,
  Wallet,
  Image,
  Coins,
  Building2,
  Flame,
  Timer,
  Star,
  Heart,
  Check,
  X,
  AlertCircle,
  Info,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  Plus,
  Minus,
  Edit,
  Trash2,
  Settings,
  Search,
  Filter,
  Download,
  Upload,
  Copy,
  Share2,
  ExternalLink,
  Link,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  Shield,
  ShieldCheck,
  ShieldAlert,
  User,
  Users,
  UserCheck,
  UserPlus,
  UserMinus,
  Mail,
  Phone,
  MessageCircle,
  MessageSquare,
  Send,
  Bell,
  BellRing,
  Home,
  Building,
  Store,
  ShoppingCart,
  ShoppingBag,
  Package,
  Box,
  Archive,
  Folder,
  File,
  FileText,
  FileCode,
  FileImage,
  Calendar,
  Clock,
  History,
  RefreshCw,
  RotateCw,
  Loader2,
  Play,
  Pause,
  StopCircle,
  FastForward,
  Rewind,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Camera,
  CameraOff,
  Video,
  VideoOff,
  Monitor,
  Smartphone,
  Laptop,
  Cpu,
  HardDrive,
  Server,
  Database,
  Cloud,
  CloudDownload,
  CloudUpload,
  Wifi,
  WifiOff,
  Globe,
  Map,
  MapPin,
  Navigation,
  Compass,
  Target,
  Award,
  Medal,
  Crown,
  Sparkles,
  Zap,
  Sun,
  Moon,
  CloudRain,
  CloudSnow,
  Wind,
  Droplet,
  Thermometer,
  Umbrella,
  Coffee,
  Pizza,
  Apple,
  Cherry,
  Grape,
  Carrot,
  Cookie,
  Cake,
  Beer,
  Wine,
  Milk,
  Sandwich,
  Soup,
  Fish,
  Egg,
  Candy,
  Heart as HeartIcon,
  Brain,
  Smile,
  Frown,
  Meh,
  ThumbsUp,
  ThumbsDown,
  Handshake,
  Hand,
  Fingerprint,
  Activity,
  Anchor,
  Aperture,
  BookOpen,
  Book,
  Bookmark,
  Briefcase,
  Calculator,
  Camera as CameraIcon,
  Cast,
  CheckCircle,
  CheckSquare,
  Circle,
  CircleDot,
  CircleEllipsis,
  CircleSlash,
  Clipboard,
  ClipboardCheck,
  ClipboardCopy,
  ClipboardList,
  ClipboardX,
  Code,
  Code2,
  Codesandbox,
  Command,
  Compass as CompassIcon,
  CreditCard,
  Crop,
  Crosshair,
  Disc,
  DollarSign,
  Euro,
  Feather,
  Flag,
  FolderOpen,
  Framer,
  Gamepad2,
  Ghost,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Github,
  Gitlab,
  GraduationCap,
  Grid3x3,
  Hash,
  Headphones,
  HelpCircle,
  Hexagon,
  Highlighter,
  Image as ImageIcon,
  Inbox,
  Infinity,
  Instagram,
  Layers,
  Layout,
  LifeBuoy,
  Link2,
  Linkedin,
  List,
  ListOrdered,
  Loader,
  LogIn,
  LogOut,
  Maximize,
  Maximize2,
  Menu,
  MessageCircle as MessageCircleIcon,
  Minimize,
  Minimize2,
  Monitor as MonitorIcon,
  MoreHorizontal,
  MoreVertical,
  Mountain,
  Move,
  Music,
  Network,
  Octagon,
  Package as PackageIcon,
  Palette,
  Paperclip,
  PenTool,
  Percent,
  PersonStanding,
  Phone as PhoneIcon,
  PieChart,
  Pin,
  Play as PlayIcon,
  Plug,
  PlusCircle,
  PlusSquare,
  Pocket,
  Power,
  Printer,
  QrCode,
  Radio,
  Receipt,
  RectangleHorizontal,
  RectangleVertical,
  Repeat,
  Reply,
  Rewind as RewindIcon,
  Rss,
  Save,
  Scale,
  Scan,
  Scissors,
  ScrollText,
  Search as SearchIcon,
  Send as SendIcon,
  SeparatorHorizontal,
  SeparatorVertical,
  Settings as SettingsIcon,
  Settings2,
  Share,
  ShieldCheck as ShieldCheckIcon,
  ShoppingBag as ShoppingBagIcon,
  Shuffle,
  SidebarClose,
  SidebarOpen,
  Signal,
  Slash,
  Sliders,
  Smartphone as SmartphoneIcon,
  Sparkle,
  Square,
  SquareDot,
  Star as StarIcon,
  StickyNote,
  Sunrise,
  Sunset,
  Table,
  Tablet,
  Tag,
  Tags,
  Target as TargetIcon,
  Terminal,
  TestTube,
  TestTube2,
  TextCursor,
  Ticket,
  ToggleLeft,
  ToggleRight,
  Trash,
  TreePine,
  TrendingDown,
  TrendingUp,
  Triangle,
  Truck,
  Tv,
  Twitter,
  Type,
  Umbrella as UmbrellaIcon,
  Underline,
  Undo,
  Unlink,
  Upload as UploadIcon,
  User as UserIcon,
  UserCheck as UserCheckIcon,
  UserMinus as UserMinusIcon,
  UserPlus as UserPlusIcon,
  Users as UsersIcon,
  UserX,
  Video as VideoIcon,
  Voicemail,
  Volume,
  VolumeX as VolumeXIcon,
  Wallet as WalletIcon,
  Watch,
  Waves,
  Webcam,
  Wifi as WifiIcon,
  Wind as WindIcon,
  X as XIcon,
  Youtube,
  Zap as ZapIcon,
  ZoomIn,
  ZoomOut,
  AlertTriangle,
  type LucideIcon
} from 'lucide-react';

// Comprehensive emoji to Lucide icon mapping
export const emojiToLucideMap: Record<string, LucideIcon> = {
  // Gift & Rewards
  '🎁': Gift,
  '🎉': Sparkles,
  '🎊': Sparkles,
  '🏆': Trophy,
  '🥇': Medal,
  '🥈': Medal,
  '🥉': Medal,
  '🏅': Award,
  '👑': Crown,
  '💎': Gem,
  '💰': Coins,
  '💵': DollarSign,
  '💶': Euro,
  '💸': DollarSign,
  '🪙': Coins,
  
  // Navigation & Actions
  '🚀': Rocket,
  '✈️': Send,
  '➡️': ArrowRight,
  '⬅️': ArrowLeft,
  '⬆️': ArrowUp,
  '⬇️': ArrowDown,
  '↗️': ArrowRight,
  '↖️': ArrowLeft,
  '↘️': ArrowRight,
  '↙️': ArrowLeft,
  '🔄': RefreshCw,
  '🔃': RotateCw,
  '⏮️': Rewind,
  '⏭️': FastForward,
  '⏯️': Play,
  '⏸️': Pause,
  '⏹️': StopCircle,
  
  // Status & Feedback
  '✅': CheckCircle,
  '✔️': Check,
  '❌': XIcon,
  '❗': AlertCircle,
  '❓': HelpCircle,
  '⚠️': AlertTriangle,
  '🔥': Flame,
  '⚡': Zap,
  '✨': Sparkles,
  '⭐': Star,
  '🌟': Star,
  '💫': Sparkles,
  
  // Wallet & Finance
  '👛': Wallet,
  '💳': CreditCard,
  '🏦': Building2,
  '🏪': Store,
  '🛒': ShoppingCart,
  '🛍️': ShoppingBag,
  
  // Files & Media
  '🖼️': Image,
  '📷': Camera,
  '📸': Camera,
  '🎥': Video,
  '📹': Video,
  '🎬': Video,
  '🎭': Palette,
  '🎨': Palette,
  '📁': Folder,
  '📂': FolderOpen,
  '📄': FileText,
  '📃': File,
  '📋': Clipboard,
  '📊': PieChart,
  '📈': TrendingUp,
  '📉': TrendingDown,
  
  // Communication
  '💬': MessageCircle,
  '💭': MessageSquare,
  '🗨️': MessageCircle,
  '📢': Bell,
  '🔔': Bell,
  '🔕': BellRing,
  '📧': Mail,
  '✉️': Mail,
  '📞': Phone,
  '📱': Smartphone,
  
  // Security & Privacy
  '🔒': Lock,
  '🔓': Unlock,
  '🔐': Key,
  '🔑': Key,
  '🛡️': Shield,
  '🔰': ShieldCheck,
  '⚔️': ShieldAlert,
  
  // Time & Date
  '⏰': Clock,
  '⏱️': Timer,
  '⏲️': Timer,
  '🕐': Clock,
  '📅': Calendar,
  '📆': Calendar,
  '🗓️': Calendar,
  
  // Education & Learning
  '📚': BookOpen,
  '📖': Book,
  '📕': Book,
  '📗': Book,
  '📘': Book,
  '📙': Book,
  '🎓': GraduationCap,
  '✏️': PenTool,
  '🖊️': PenTool,
  '🖋️': Feather,
  
  // Technology
  '💻': Laptop,
  '🖥️': Monitor,
  '⌨️': Terminal,
  '🖱️': Crosshair,
  '💾': Save,
  '💿': Disc,
  '📀': Disc,
  '🔌': Plug,
  '🔋': Activity,
  '📡': Wifi,
  '📶': Signal,
  '📳': Smartphone,
  
  // People & Emotions
  '👤': User,
  '👥': Users,
  '👨': User,
  '👩': User,
  '👦': User,
  '👧': User,
  '😀': Smile,
  '😃': Smile,
  '😄': Smile,
  '😁': Smile,
  '😆': Smile,
  '😅': Smile,
  '😂': Smile,
  '🙂': Smile,
  '😊': Smile,
  '😇': Smile,
  '😢': Frown,
  '😭': Frown,
  '😐': Meh,
  '😑': Meh,
  '👍': ThumbsUp,
  '👎': ThumbsDown,
  '👏': Handshake,
  '🤝': Handshake,
  '🙏': Hand,
  '❤️': Heart,
  '💙': Heart,
  '💚': Heart,
  '💛': Heart,
  '💜': Heart,
  '🖤': Heart,
  '🤍': Heart,
  '💔': Heart,
  
  // Nature & Weather
  '☀️': Sun,
  '🌞': Sun,
  '🌙': Moon,
  '🌛': Moon,
  '🌜': Moon,
  '☁️': Cloud,
  '🌧️': CloudRain,
  '⛈️': CloudRain,
  '🌩️': Zap,
  '🌨️': CloudSnow,
  '❄️': CloudSnow,
  '☃️': CloudSnow,
  '🌬️': Wind,
  '💨': Wind,
  '💧': Droplet,
  '💦': Droplet,
  '☔': Umbrella,
  '🌊': Waves,
  '🏔️': Mountain,
  '🌲': TreePine,
  '🌳': TreePine,
  
  // Tools & Settings
  '🔧': Settings,
  '🔨': Settings2,
  '⚙️': Settings,
  '🛠️': Settings2,
  '⚒️': Settings2,
  '🔍': Search,
  '🔎': Search,
  '🔦': Search,
  '🔭': Search,
  '🔬': TestTube2,
  '🧪': TestTube,
  '⚗️': TestTube2,
  '🗑️': Trash2,
  '✂️': Scissors,
  '📌': Pin,
  '📍': MapPin,
  '🏴': Flag,
  '🏳️': Flag,
  '🚩': Flag,
  
  // Miscellaneous
  '🌐': Globe,
  '🌍': Globe,
  '🌎': Globe,
  '🌏': Globe,
  '🗺️': Map,
  '🧭': Compass,
  '🎯': Target,
  '🎲': Gamepad2,
  '🎮': Gamepad2,
  '🎪': Mountain,
  '🎡': Circle,
  '🎢': TrendingUp,
  '🎠': Mountain,
  '🎟️': Ticket,
  '🏠': Home,
  '🏡': Home,
  '🏢': Building,
  '🏬': Store,
  '🏭': Building2,
  '🏛️': Building2,
  '🚪': RectangleVertical,
  '🪟': RectangleHorizontal,
  '🛏️': RectangleHorizontal,
  '🪑': Square,
  '🍔': Sandwich,
  '🍕': Pizza,
  '🍎': Apple,
  '🍒': Cherry,
  '🍇': Grape,
  '🥕': Carrot,
  '🍪': Cookie,
  '🎂': Cake,
  '🍺': Beer,
  '🍷': Wine,
  '🥛': Milk,
  '🍲': Soup,
  '🐟': Fish,
  '🥚': Egg,
  '🍬': Candy,
  '☕': Coffee,
  '🧠': Brain,
  '👻': Ghost,
  '🤖': Cpu,
  '👾': Gamepad2,
  '🚦': Activity,
  '⚓': Anchor,
  '🎸': Music,
  '🎵': Music,
  '🎶': Music,
  '🎼': Music,
  '🎤': Mic,
  '🎧': Headphones,
  '📻': Radio,
  '📺': Tv,
  '📽️': Video,
  '🎞️': Video,
  '📸': Camera,
  '📷': Camera,
  '🖨️': Printer,
  '⌚': Watch,
  '⏳': Timer,
  '⌛': Timer,
  '📏': SeparatorHorizontal,
  '📐': Triangle,
  '✏️': PenTool,
  '✒️': PenTool,
  '🖌️': Palette,
  '🖍️': Highlighter,
  '📝': ClipboardList,
  '💼': Briefcase,
  '📌': Pin,
  '📍': MapPin,
  '📎': Paperclip,
  '🔗': Link2,
  '⛓️': Link,
  '🧲': Anchor,
  '💡': LifeBuoy,
  '🔌': Plug,
  '🔋': Activity,
  '🔆': Sun,
  '🔅': Sunrise,
  '🌅': Sunrise,
  '🌄': Sunset,
  '🌠': Sparkles,
  '🎆': Sparkles,
  '🎇': Sparkles,
  '🌈': Palette,
  '🌂': Umbrella,
  '☂️': Umbrella,
  '☃️': CloudSnow,
  '⛄': CloudSnow,
  '❄️': CloudSnow,
  '🌬️': Wind,
  '💨': Wind,
  '🌪️': Wind,
  '🌫️': Cloud,
  '🔥': Flame,
  '💥': Zap,
  '✨': Sparkles,
  '🌟': Star,
  '⭐': Star,
  '💫': Sparkles,
  '☄️': Rocket,
  '💥': Zap,
  '🔥': Flame,
  '🌋': Mountain,
  '🗻': Mountain,
  '🏔️': Mountain,
  '⛰️': Mountain,
  '🗿': Square,
  '🗽': Building2,
  '🗼': Building2,
  '⛲': Droplet,
  '⛺': Mountain,
  '🏕️': Mountain,
  '🏖️': Waves,
  '🏜️': Mountain,
  '🏝️': Mountain,
  '🏞️': Mountain,
  '🚦': Activity,
  '🚥': Activity,
  '🚧': AlertTriangle,
  '⛔': CircleSlash,
  '🛑': Octagon,
  '⚠️': AlertTriangle,
  '☢️': AlertTriangle,
  '☣️': AlertTriangle,
  '⬆️': ArrowUp,
  '↗️': ArrowUp,
  '➡️': ArrowRight,
  '↘️': ArrowDown,
  '⬇️': ArrowDown,
  '↙️': ArrowDown,
  '⬅️': ArrowLeft,
  '↖️': ArrowLeft,
  '↕️': SeparatorVertical,
  '↔️': SeparatorHorizontal,
  '↩️': Reply,
  '↪️': Reply,
  '⤴️': ArrowUp,
  '⤵️': ArrowDown,
  '🔀': Shuffle,
  '🔁': Repeat,
  '🔂': Repeat,
  '▶️': Play,
  '⏸️': Pause,
  '⏯️': Play,
  '◀️': ArrowLeft,
  '⏮️': Rewind,
  '⏭️': FastForward,
  '⏩': FastForward,
  '⏪': Rewind,
  '🔼': ChevronUp,
  '⏫': ChevronUp,
  '🔽': ChevronDown,
  '⏬': ChevronDown,
  '⏹️': StopCircle,
  '⏺️': Circle,
  '⏏️': Upload,
  '🔅': Sun,
  '🔆': Sun,
  '🔇': VolumeX,
  '🔈': Volume,
  '🔉': Volume2,
  '🔊': Volume2,
  '📢': Bell,
  '📣': Bell,
  '📯': Bell,
  '🔕': BellRing,
  '🎵': Music,
  '🎶': Music,
  '♻️': RefreshCw,
  '🔱': Target,
  '📛': Tag,
  '🔰': ShieldCheck,
  '⭕': Circle,
  '✅': CheckCircle,
  '☑️': CheckSquare,
  '✔️': Check,
  '❌': X,
  '❎': XIcon,
  '➕': Plus,
  '➖': Minus,
  '➗': Slash,
  '✖️': X,
  '♾️': Infinity,
  '💲': DollarSign,
  '💱': DollarSign,
  '™️': Codesandbox,
  '©️': Circle,
  '®️': Circle,
  '‼️': AlertCircle,
  '⁉️': HelpCircle,
  '❓': HelpCircle,
  '❔': HelpCircle,
  '❕': AlertCircle,
  '❗': AlertCircle,
  '〰️': Waves,
  '💤': Meh,
  '🅰️': Type,
  '🆎': Type,
  '🅱️': Type,
  '🆑': Type,
  '🆒': Type,
  '🆓': Type,
  'ℹ️': Info,
  '🆔': CreditCard,
  'Ⓜ️': Circle,
  '🆕': PlusCircle,
  '🆖': XIcon,
  '🅾️': Circle,
  '🆗': CheckCircle,
  '🅿️': Square,
  '🆘': AlertTriangle,
  '🆙': TrendingUp,
  '🆚': Zap,
  '🈁': Square,
  '🈂️': Square,
  '🈷️': Square,
  '🈶': Square,
  '🈯': Square,
  '🉐': Square,
  '🈹': Square,
  '🈚': Square,
  '🈲': Square,
  '🉑': Square,
  '🈸': Square,
  '🈴': Square,
  '🈳': Square,
  '㊗️': Square,
  '㊙️': Square,
  '🈺': Square,
  '🈵': Square,
  '🔴': Circle,
  '🟠': Circle,
  '🟡': Circle,
  '🟢': Circle,
  '🔵': Circle,
  '🟣': Circle,
  '🟤': Circle,
  '⚫': Circle,
  '⚪': Circle,
  '🟥': Square,
  '🟧': Square,
  '🟨': Square,
  '🟩': Square,
  '🟦': Square,
  '🟪': Square,
  '🟫': Square,
  '⬛': Square,
  '⬜': Square,
  '◼️': SquareDot,
  '◻️': Square,
  '◾': SquareDot,
  '◽': Square,
  '▪️': SquareDot,
  '▫️': Square,
  '🔶': Hexagon,
  '🔷': Hexagon,
  '🔸': Triangle,
  '🔹': Triangle,
  '🔺': Triangle,
  '🔻': Triangle,
  '💠': Hexagon,
  '🔘': CircleDot,
  '🔳': Square,
  '🔲': SquareDot,
};

// Default icon for unmapped emojis
export const defaultIcon = HelpCircle;

// Helper function to get Lucide icon for an emoji
export function getLucideIconForEmoji(emoji: string): LucideIcon {
  return emojiToLucideMap[emoji] || defaultIcon;
}

// Helper to check if a string contains emojis
export function containsEmoji(text: string): boolean {
  const emojiRegex = /[\u{1F300}-\u{1F9FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]|[\u{1F000}-\u{1F02F}]|[\u{1F0A0}-\u{1F0FF}]|[\u{1F100}-\u{1F64F}]|[\u{1F680}-\u{1F6FF}]|[\u{1F900}-\u{1F9FF}]|[\u{1FA70}-\u{1FAFF}]|[\u{2000}-\u{206F}]|[\u{2190}-\u{21FF}]|[\u{2300}-\u{23FF}]|[\u{2460}-\u{24FF}]|[\u{25A0}-\u{25FF}]|[\u{2B00}-\u{2BFF}]|[\u{3000}-\u{303F}]|[\u{3200}-\u{32FF}]|[\u{1F000}-\u{1F9FF}]|[\u{1FA00}-\u{1FA6F}]/gu;
  return emojiRegex.test(text);
}

// Helper to extract emojis from text
export function extractEmojis(text: string): string[] {
  const emojiRegex = /[\u{1F300}-\u{1F9FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]|[\u{1F000}-\u{1F02F}]|[\u{1F0A0}-\u{1F0FF}]|[\u{1F100}-\u{1F64F}]|[\u{1F680}-\u{1F6FF}]|[\u{1F900}-\u{1F9FF}]|[\u{1FA70}-\u{1FAFF}]|[\u{2000}-\u{206F}]|[\u{2190}-\u{21FF}]|[\u{2300}-\u{23FF}]|[\u{2460}-\u{24FF}]|[\u{25A0}-\u{25FF}]|[\u{2B00}-\u{2BFF}]|[\u{3000}-\u{303F}]|[\u{3200}-\u{32FF}]|[\u{1F000}-\u{1F9FF}]|[\u{1FA00}-\u{1FA6F}]/gu;
  return text.match(emojiRegex) || [];
}

// Helper to replace emojis in text with icon placeholders
export function replaceEmojisWithPlaceholders(text: string): { text: string; emojis: string[] } {
  const emojis = extractEmojis(text);
  let processedText = text;
  
  emojis.forEach((emoji, index) => {
    processedText = processedText.replace(emoji, `__ICON_${index}__`);
  });
  
  return { text: processedText, emojis };
}